---
- hosts: ubuntu_14
  tasks:

  - name: Install nginx package
    apt: name=nginx update_cache=yes

  - name: Copy config /etc/nginx/sites-available/default
    copy: src=/etc/ansible/playbooks/nginx_apache_modphp/conf/nginx/sites-available/default  dest=/etc/nginx/sites-available/default

  - name: Copy config /etc/nginx/nginx.conf
    copy: src=/etc/ansible/playbooks/nginx_apache_modphp/conf/nginx/nginx.conf  dest=/etc/nginx/nginx.conf

  - name: Starting nginx service
    service: name=nginx state=started

  - name: Install apache2 package
    apt: name=apache2 update_cache=yes

  - name: Copy config /etc/apache2/apache2.conf
    copy: src=/etc/ansible/playbooks/nginx_apache_modphp/conf/apache2/apache2.conf  dest=/etc/apache2/apache2.conf

  - name: Copy config /etc/apache2/ports.conf
    copy: src=/etc/ansible/playbooks/nginx_apache_modphp/conf/apache2/ports.conf  dest=/etc/apache2/ports.conf

  - name: Copy config /etc/apache2/sites-available/000-default.conf
    copy: src=/etc/ansible/playbooks/nginx_apache_modphp/conf/apache2/sites-available/000-default.conf  dest=/etc/apache2/sites-available/000-default.conf

  - name: Install libapache2-mod-php5
    apt: name=libapache2-mod-php5 update_cache=yes

  - name: Starting apache2 service
    service: name=apache2 state=started

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
