---
- hosts: ubuntu_14
  tasks:

  - name: Install nginx package
    apt: name=nginx update_cache=yes

  - name: Copy config /etc/nginx/sites-available/default
    template: src=conf/nginx/sites-available/default  dest=/etc/nginx/sites-available/default
    notify:
    - restart nginx

  - name: ensure nginx is running
    service: name=nginx state=started

  - name: Copy config /etc/nginx/nginx.conf
    template: src=conf/nginx/nginx.conf  dest=/etc/nginx/nginx.conf
    notify:
    - restart nginx

  - name: ensure nginx is running
    service: name=nginx state=started

  - name: Install apache2 package
    apt: name=apache2 update_cache=yes

  - name: Copy config /etc/apache2/apache2.conf
    template: src=conf/apache2/apache2.conf  dest=/etc/apache2/apache2.conf
    notify:
    - restart apache2

  - name: ensure apache2 is running
    service: name=apache2 state=started

  - name: Copy config /etc/apache2/ports.conf
    template: src=conf/apache2/ports.conf  dest=/etc/apache2/ports.conf
    notify:
    - restart apache2

  - name: ensure apache2 is running
    service: name=apache2 state=started

  - name: Copy config /etc/apache2/sites-available/000-default.conf
    template: src=conf/apache2/sites-available/000-default.conf  dest=/etc/apache2/sites-available/000-default.conf
    notify:
    - restart apache2

  - name: ensure apache2 is running
    service: name=apache2 state=started

  - name: Install libapache2-mod-php5
    apt: name=libapache2-mod-php5 update_cache=yes

  - name: Starting apache2 service
    service: name=apache2 state=started

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
  - name: restart apache2
    service: name=apache2 state=restarted
